/**
 * Fixed taxonomies used by attribute enrichment (B2), retrieval
 * (B3), and the chat tool schema (B4). Anything not in these
 * lists is not a valid enrichment output.
 */

export const CATEGORIES = [
  "jeans",
  "pants",
  "shorts",
  "skirt",
  "dress",
  "top",
  "tee",
  "sweater",
  "jacket",
  "coat",
  "blazer",
  "shoes",
  "sneakers",
  "sandals",
  "boots",
  "bag",
  "jewelry",
  "earrings",
  "necklace",
  "sunglasses",
  "swim",
  "activewear",
  "accessory",
  "beauty",
  "home",
  "other",
] as const;

export type Category = (typeof CATEGORIES)[number];

export const COLORS = [
  "black",
  "white",
  "ivory",
  "cream",
  "beige",
  "tan",
  "brown",
  "grey",
  "blue",
  "light-blue",
  "navy",
  "green",
  "olive",
  "red",
  "burgundy",
  "pink",
  "blush",
  "orange",
  "yellow",
  "gold",
  "silver",
  "multi",
] as const;

export type Color = (typeof COLORS)[number];

/** Any color that reads as a "blue family" match. Used by the
 *  denim-implies-blue rule in parseQuery. */
export const BLUE_FAMILY: readonly Color[] = ["blue", "light-blue", "navy"];

/** Color synonyms mapped into the fixed lexicon. Keys are the
 *  lowercase raw token; values are the canonical color. */
export const COLOR_SYNONYMS: Record<string, Color> = {
  black: "black",
  jet: "black",
  onyx: "black",
  white: "white",
  ivory: "ivory",
  cream: "cream",
  ecru: "cream",
  bone: "cream",
  beige: "beige",
  camel: "tan",
  tan: "tan",
  taupe: "tan",
  brown: "brown",
  chocolate: "brown",
  espresso: "brown",
  grey: "grey",
  gray: "grey",
  charcoal: "grey",
  blue: "blue",
  cobalt: "blue",
  royal: "blue",
  "light-blue": "light-blue",
  "light blue": "light-blue",
  sky: "light-blue",
  denim: "blue",
  indigo: "navy",
  navy: "navy",
  "dark-wash": "navy",
  "dark wash": "navy",
  green: "green",
  emerald: "green",
  forest: "green",
  olive: "olive",
  khaki: "olive",
  red: "red",
  crimson: "red",
  burgundy: "burgundy",
  wine: "burgundy",
  merlot: "burgundy",
  pink: "pink",
  fuchsia: "pink",
  hotpink: "pink",
  blush: "blush",
  rose: "blush",
  orange: "orange",
  rust: "orange",
  terracotta: "orange",
  yellow: "yellow",
  mustard: "yellow",
  butter: "yellow",
  gold: "gold",
  brass: "gold",
  silver: "silver",
  chrome: "silver",
  multi: "multi",
  print: "multi",
  floral: "multi",
};

/** Category synonyms mapped into the fixed lexicon. Keys lowercase. */
export const CATEGORY_SYNONYMS: Record<string, Category> = {
  jeans: "jeans",
  jean: "jeans",
  denim: "jeans",
  pants: "pants",
  pant: "pants",
  trouser: "pants",
  trousers: "pants",
  slacks: "pants",
  shorts: "shorts",
  short: "shorts",
  skirt: "skirt",
  midi: "skirt",
  maxi: "skirt",
  dress: "dress",
  dresses: "dress",
  gown: "dress",
  top: "top",
  tops: "top",
  blouse: "top",
  shirt: "top",
  cami: "top",
  tank: "top",
  tee: "tee",
  "t-shirt": "tee",
  tshirt: "tee",
  sweater: "sweater",
  cardigan: "sweater",
  pullover: "sweater",
  jumper: "sweater",
  knit: "sweater",
  jacket: "jacket",
  moto: "jacket",
  bomber: "jacket",
  coat: "coat",
  trench: "coat",
  parka: "coat",
  puffer: "coat",
  blazer: "blazer",
  shoes: "shoes",
  shoe: "shoes",
  loafer: "shoes",
  loafers: "shoes",
  mule: "shoes",
  mules: "shoes",
  heel: "shoes",
  heels: "shoes",
  flat: "shoes",
  flats: "shoes",
  pump: "shoes",
  pumps: "shoes",
  sneakers: "sneakers",
  sneaker: "sneakers",
  trainer: "sneakers",
  trainers: "sneakers",
  sandals: "sandals",
  sandal: "sandals",
  slide: "sandals",
  slides: "sandals",
  boots: "boots",
  boot: "boots",
  bootie: "boots",
  booties: "boots",
  bag: "bag",
  bags: "bag",
  tote: "bag",
  clutch: "bag",
  crossbody: "bag",
  purse: "bag",
  handbag: "bag",
  jewelry: "jewelry",
  jewellery: "jewelry",
  bracelet: "jewelry",
  ring: "jewelry",
  earrings: "earrings",
  earring: "earrings",
  hoops: "earrings",
  hoop: "earrings",
  studs: "earrings",
  necklace: "necklace",
  necklaces: "necklace",
  pendant: "necklace",
  chain: "necklace",
  sunglasses: "sunglasses",
  shades: "sunglasses",
  swim: "swim",
  bikini: "swim",
  swimsuit: "swim",
  activewear: "activewear",
  legging: "activewear",
  leggings: "activewear",
  sportsbra: "activewear",
  accessory: "accessory",
  accessories: "accessory",
  scarf: "accessory",
  belt: "accessory",
  hat: "accessory",
  beauty: "beauty",
  serum: "beauty",
  moisturizer: "beauty",
  lipstick: "beauty",
  mascara: "beauty",
  home: "home",
  candle: "home",
  vase: "home",
};

/** Material lexicon used by the enrichment prompt. Not gated for
 *  retrieval yet (spec calls out attributes.materials as tracked but
 *  we filter on category + color at the query layer). */
export const MATERIALS = [
  "linen",
  "cotton",
  "silk",
  "cashmere",
  "wool",
  "leather",
  "suede",
  "denim",
  "satin",
  "velvet",
  "knit",
  "mesh",
  "nylon",
  "polyester",
] as const;

export const STYLES = [
  "casual",
  "dressy",
  "workwear",
  "beach",
  "evening",
  "sport",
  "streetwear",
  "coastal",
  "editorial",
  "minimalist",
  "boho",
  "preppy",
] as const;

export function normalizeColor(raw: string): Color | null {
  const s = raw.trim().toLowerCase();
  const mapped = COLOR_SYNONYMS[s];
  if (mapped) return mapped;
  const collapsed = s.replace(/[-\s]/g, "");
  for (const [k, v] of Object.entries(COLOR_SYNONYMS)) {
    if (k.replace(/[-\s]/g, "") === collapsed) return v;
  }
  return null;
}

export function normalizeCategory(raw: string): Category | null {
  const s = raw.trim().toLowerCase();
  const mapped = CATEGORY_SYNONYMS[s];
  if (mapped) return mapped;
  return null;
}
